# core/localization.py

TRANSLATIONS = {
    "en": {
        # Main App & General UI
        "app_title": "Welcome to Your Study Dashboard",
        "debug_mode_toggle": "🐞 Enable Debug Mode",
        "clear_cache_button": "🔄 Clear Cache & Reload Data",
        "cache_cleared_success": "Cache cleared successfully! Data will be reloaded.",
        "progress_overview_header": "📊 Progress Overview",
        "practice_english_button": "Start Learning 🇨🇦",
        "practice_french_button": "Start Learning 🇫🇷",
        "dashboard_title": "Study Dashboard 🇨🇦",
        "change_language_button": "🌐 Change Language",
        "active_words_metric": "⚡ Active Words",
        "accuracy_metric": "🎯 Overall Accuracy",
        "sessions_metric": "🗓️ Sessions Completed",
        "practice_header": "🧠 Practice Modes",
        "reinforce_header": "💪 Reinforce & Master",
        "analyze_header": "✍️ Analyze & Create",
        "back_to_dashboard": "🔙 Back to Dashboard",
        "no_active_words": "⚠️ No active words for the quiz. Please activate some in the Stats & Manager page.",
        "mastery_pie_chart_title": "🏆 Overall Mastery",
        "progress_distribution_title": "📈 Progress Distribution",
        "no_progress_data": "No progress data to display.",
        "error_ranking_title": "🔥 Difficulty Ranking (Top Errors)",
        "see_full_ranking_button": "👀 See full ranking",
        "no_errors_to_rank": "✅ No errors recorded for active words yet. Great job!",
        "age_ranking_title": "⏳ Longevity Ranking (Oldest Words)",
        "no_words_to_rank_by_age": "✅ No active words to rank by age.",

        # Button Names
        "anki_quiz_button": "🗃️ ANKI Quiz",
        "gpt_quiz_button": "🤖 GPT Quiz",
        "mixed_quiz_button": "🔄 Mixed Quiz",
        "cloze_quiz_button": "📝 Cloze Quiz",
        "review_mode_button": "🔁 Review Mode",
        "focus_mode_button": "🎯 Focus Mode",
        "writing_mode_button": "✍️ Writing Mode",
        "sentence_writing_button": "🖋️ Sentence Practice",
        "stats_button": "📊 Stats & Manager",

        # Quiz UI (Shared)
        "how_many_questions": "How many questions do you want to answer?",
        "start_quiz": "▶️ Start Quiz",
        "no_valid_questions": "❌ No valid questions found for the selected filters. Please try 'Random' or another type.",
        "quiz_progress": "Progress: {idx}/{total} questions",
        "check_button": "✔️ Check",
        "next_button": "➡️ Next",
        "cancel_quiz": "✖️ Cancel Quiz",
        "correct_answer": "✅ Correct!",
        "incorrect_answer": "❌ Incorrect! Correct answer: {correct}",
        "final_result": "🎉 Final result: {correct_count} correct, {error_count} errors | Score: {score}%",
        "finish_button": "🏁 Finish",
        "choose_exercise_type": "Choose the exercise type:",

        # ANKI Quiz
        "anki_quiz_title": "ANKI Quiz 🇨🇦",
        "word_meaning_anki": "1-Word-Meaning",
        "translation_anki": "2-Word-Translation",
        "synonym_anki": "3-Synonym",
        "gap_fill_anki": "4-Gap-Fill",
        "reading_anki": "5-Reading-Comprehension",
        
        # GPT Quiz
        "gpt_quiz_title": "GPT Quiz 🇨🇦",
        "how_many_unique_words": "How many UNIQUE WORDS to use?",
        "allow_word_repetition": "Allow word repetition?",
        "repetition_help_no": "If 'No', each word will appear only once.",
        "repetition_help_yes": "If 'Yes', the same word can appear multiple times with different exercises.",
        "option_yes": "Yes",
        "option_no": "No",
        "start_exercises": "▶️ Start Exercises",
        "cancel_exercises": "✖️ Cancel Exercises",

        # Mixed Quiz
        "mixed_quiz_info": "This mode combines questions from ANKI and GPT quizzes.",

        # Review Mode
        "review_mode_title": "Review Mode 🇨🇦",
        "review_info": "This mode tests your knowledge of mastered (inactive) words. If you get a word wrong, it will be reactivated and its progress reset.",
        "how_many_words_to_review": "How many words do you want to review?",
        "start_review": "▶️ Start Review",
        "cancel_review": "✖️ Cancel Review",
        "review_complete": "🎉 Review complete! Score: {score}%",
        "words_reactivated": "⚠️ The following words were reactivated and their progress reset: {words}",
        "no_inactive_words_info": "You have no mastered words to review yet. Keep practicing in other modes!",
        
        # Focus Mode
        "focus_mode_info": "Choose a word to practice all its available exercises intensively.",
        "choose_focus_word": "Select a word to focus on:",
        "start_focus_button": "▶️ Start Focus on '{word}'",
        "choose_another_word": "🔄 Choose Another Word",
        "practicing_with": "Practicing with:",
        
        # Writing Mode
        "writing_info": "Practice your writing. Choose a word from the list to write or review, or draw one randomly.",
        "choose_word_label": "Choose a word to practice or review:",
        "random_word_button": "🎲 Draw New Word",
        "text_area_label": "Write or edit your text here:",
        "words_metric": "Words",
        "chars_metric": "Characters",
        "paragraphs_metric": "Paragraphs",
        "save_text_button": "💾 Save Text",
        "empty_text_error": "The text field is empty.",
        "text_saved_success": "Text for word '{word}' saved successfully!",

        # Stats Page
        "db_summary_header": "📊 Database Summary",
        "total_words_metric": "📚 Total Words",
        "inactive_words_metric": "💤 Inactive Words",
        "anki_source_metric": "🗃️ ANKI Source",
        "gpt_source_metric": "🤖 GPT Source",
        "import_log_header": "⚠️ Data Import Log",
        "import_log_warning": "Problems were found while reading the data files. The following lines/files were ignored:",
        "vocab_manager_header": "🗂️ Vocabulary Manager",
        "filter_by_source": "Filter by Source:",
        "filter_by_date": "Filter by Add Date:",
        "delete_filtered_button": "🗑️ Delete All Filtered",
        "show_exercise_details": "Show details by exercise",
        "col_active": "Active?",
        "col_delete": "Delete?",
        "col_word": "Word",
        "col_source": "Source",
        "col_progress": "Progress",
        "col_status": "Status",
        "col_status_help": "🏆 indicates the number of times the word has been mastered!",
        "save_active_status_button": "💾 Save 'Active' Status",
        "delete_selected_button": "🗑️ Delete Selected",
        "written_texts_log_header": "✍️ Written Texts Log",
        "cloze_texts_manager_header": "📝 Cloze Texts Manager",
        "danger_zone_header": "⚠️ Danger Zone",
        "danger_zone_warning": "The action below is irreversible and will erase ALL your performance history.",
        "clear_history_button": "🗑️ Clear ALL Performance History",
        "no_cloze_in_memory": "No '7-Cloze-Text' exercises found in memory.",
        "delete_cloze_button": "🗑️ Delete Selected Cloze Texts",
        "no_cloze_selected_for_deletion": "No Cloze texts were marked for deletion.",

        # Cloze Quiz
        "no_cloze_exercises_found": "No '7-Cloze-Text' exercises found in the data.",
        "select_cloze_text": "Select the text you want to practice:",
        "cloze_info": "Fill each [GAP] with one of the options. An option can only be used once.",
        "check_answers_button": "✔️ Check Answers",
        "clear_answers_button": "🔄 Clear Answers",
        "practice_another_text_button": "🔄 Practice Another Text",
        
        # Sentence Writing Module
        "sentence_writing_title": "Sentence Writing Practice ✍️",
        "no_sentence_words_found": "⚠️ No words found in 'palavras_unicas_por_tipo.txt'. Please create the file.",
        "stats_header": "📊 Statistics",
        "total_words_metric_sentence": "Total Words",
        "completed_words_metric": "Completed (5/5)",
        "partial_words_metric": "In Progress (1-4)",
        "untouched_words_metric": "Untouched (0/5)",
        "word_selection_header": "🔍 Word Selection",
        "filter_by_status": "Filter by status:",
        "choose_word_sentence": "Or choose a specific word:",
        "class_level_label": "Class",
        "reference_sentence_label": "Reference",
        "your_sentences_header": "Your Sentences",
        "feedback_header": "Feedback / Comments",
        "save_button_sentence": "💾 Save Sentences & Comment",
        "save_success_sentence": "✅ Saved successfully for word '{word}'!",
        "export_options_header": "📤 Export Options",
        "export_all_button": "Download All (TXT)",
        "export_filtered_button": "Download Filtered (TXT)",
        "feedback_placeholder": "Feedback here...",
        "no_words_in_filter": "No words for this filter",
        "filter_by_level": "Filter by Level:",
        "filter_by_class": "Filter by Class:",
        "activity_chart_header": "📊 Daily Activity",
        "last_30_days_activity_title": "Sentences Written in the Last 30 Days",
        "no_activity_data": "No writing activity recorded yet. Start writing some sentences!",
        "delete_word_data_button": "🗑️ Delete Data",
        "delete_word_data_success": "All sentence data for '{word}' has been deleted.",
        "grade_label": "Grade (0-10)",
        "correction_label": "Correction",
        "average_grade_label": "Average Grade",
        "corrected_checkbox": "Corrected ✅",
        "include_comments_toggle": "Include Comments",
        "filter_by_correction_label": "Filter by Correction Status:",
        "all_sentences": "All",
        "corrected_sentences": "Corrected",
        "not_corrected_sentences": "Not Corrected",
        "include_corrections_toggle": "Include Corrections",
        "include_grades_toggle": "Include Grades",

    },
    "fr": {
        # Main App & General UI
        "app_title": "Bienvenue sur votre Tableau de Bord d'Étude",
        "debug_mode_toggle": "🐞 Activer le Mode de Débogage",
        "clear_cache_button": "🔄 Vider le Cache et Recharger",
        "cache_cleared_success": "Cache vidé avec succès ! Les données vont être rechargées.",
        "progress_overview_header": "📊 Aperçu des Progrès",
        "practice_english_button": "Start Learning 🇨🇦",
        "practice_french_button": "Start Learning 🇫🇷",
        "dashboard_title": "Tableau de bord 🇫🇷",
        "change_language_button": "🌐 Changer de Langue",
        "active_words_metric": "⚡ Mots Actifs",
        "accuracy_metric": "🎯 Précision Globale",
        "sessions_metric": "🗓️ Sessions Terminées",
        "practice_header": "🧠 Modes de Pratique",
        "reinforce_header": "💪 Renforcer & Maîtriser",
        "analyze_header": "✍️ Analyser & Créer",
        "back_to_dashboard": "🔙 Retour au Tableau de Bord",
        "no_active_words": "⚠️ Aucun mot actif pour le quiz. Veuillez en activer sur la page Stats & Gestionnaire.",
        "mastery_pie_chart_title": "🏆 Maîtrise Générale",
        "progress_distribution_title": "📈 Répartition des Progrès",
        "no_progress_data": "Aucune donnée de progression à afficher.",
        "error_ranking_title": "🔥 Classement des Difficultés (Top Erreurs)",
        "see_full_ranking_button": "👀 Voir le classement complet",
        "no_errors_to_rank": "✅ Aucune erreur enregistrée pour les mots actifs. Excellent travail !",
        "age_ranking_title": "⏳ Classement par Ancienneté",
        "no_words_to_rank_by_age": "✅ Aucun mot actif à classer par ancienneté.",
        
        # Button Names
        "anki_quiz_button": "🗃️ Quiz ANKI",
        "gpt_quiz_button": "🤖 Quiz GPT",
        "mixed_quiz_button": "🔄 Quiz Mixte",
        "cloze_quiz_button": "📝 Quiz Cloze",
        "review_mode_button": "🔁 Mode de Révision",
        "focus_mode_button": "🎯 Mode Focus",
        "writing_mode_button": "✍️ Mode d'Écriture",
        "sentence_writing_button": "🖋️ Pratique de Phrases",
        "stats_button": "📊 Stats & Gestionnaire",

        # Quiz UI (Shared)
        "how_many_questions": "Combien de questions souhaitez-vous répondre ?",
        "start_quiz": "▶️ Démarrer le Quiz",
        "no_valid_questions": "❌ Aucune question valide trouvée pour les filtres sélectionnés. Essayez 'Aléatoire' ou un autre type.",
        "quiz_progress": "Progression : {idx}/{total} questions",
        "check_button": "✔️ Vérifier",
        "next_button": "➡️ Suivant",
        "cancel_quiz": "✖️ Annuler le Quiz",
        "correct_answer": "✅ Correct !",
        "incorrect_answer": "❌ Incorrect ! La bonne réponse est : {correct}",
        "final_result": "🎉 Résultat final : {correct_count} corrects, {error_count} erreurs | Score : {score}%",
        "finish_button": "🏁 Terminer",
        "choose_exercise_type": "Choisissez le type d'exercice :",

        # ANKI Quiz
        "anki_quiz_title": "Quiz ANKI 🇫🇷",
        "word_meaning_anki": "1-Signification du mot",
        "translation_anki": "2-Traduction du mot",
        "synonym_anki": "3-Synonyme",
        "gap_fill_anki": "4-Texte à trous",
        "reading_anki": "5-Compréhension Écrite",

        # GPT Quiz
        "gpt_quiz_title": "Quiz GPT 🇫🇷",
        "how_many_unique_words": "Combien de MOTS UNIQUES utiliser ?",
        "allow_word_repetition": "Autoriser la répétition de mots ?",
        "repetition_help_no": "Si 'Non', chaque mot n'apparaîtra qu'une seule fois.",
        "repetition_help_yes": "Si 'Oui', le même mot peut apparaître plusieurs fois avec des exercices différents.",
        "option_yes": "Oui",
        "option_no": "Non",
        "start_exercises": "▶️ Démarrer les Exercices",
        "cancel_exercises": "✖️ Annuler les Exercices",

        # Mixed Quiz
        "mixed_quiz_info": "Ce mode combine des questions des modules Quiz ANKI et Quiz GPT.",

        # Review Mode
        "review_mode_title": "Mode de Révision 🇫🇷",
        "review_info": "Ce mode teste vos connaissances sur des mots maîtrisés (inactifs). En cas d'erreur, le mot sera réactivé et sa progression sera réinitialisée.",
        "how_many_words_to_review": "Combien de mots souhaitez-vous réviser ?",
        "start_review": "▶️ Démarrer la Révision",
        "cancel_review": "✖️ Annuler la Révision",
        "review_complete": "🎉 Révision terminée ! Score : {score}%",
        "words_reactivated": "⚠️ Les mots suivants ont été réactivés et leur progression réinitialisée : {words}",
        "no_inactive_words_info": "Vous n'avez pas encore de mots maîtrisés à réviser. Continuez à pratiquer dans les autres modes !",
        
        # Focus Mode
        "focus_mode_info": "Choisissez un mot pour pratiquer intensivement tous ses exercices disponibles.",
        "choose_focus_word": "Sélectionnez un mot pour vous concentrer :",
        "start_focus_button": "▶️ Démarrer le focus sur '{word}'",
        "choose_another_word": "🔄 Choisir un autre mot",
        "practicing_with": "Pratique avec :",
        
        # Writing Mode
        "writing_info": "Pratiquez votre écriture. Choisissez un mot dans la liste pour écrire ou réviser, ou tirez-en un au hasard.",
        "choose_word_label": "Choisissez un mot pour pratiquer ou réviser :",
        "random_word_button": "🎲 Tirer un nouveau mot",
        "text_area_label": "Écrivez ou modifiez votre texte ici :",
        "words_metric": "Mots",
        "chars_metric": "Caractères",
        "paragraphs_metric": "Paragraphes",
        "save_text_button": "💾 Enregistrer le texte",
        "empty_text_error": "Le champ de texte est vide.",
        "text_saved_success": "Le texte pour le mot '{word}' a été enregistré avec succès !",
        
        # Stats Page
        "db_summary_header": "📊 Résumé de la base de données",
        "total_words_metric": "📚 Mots au total",
        "inactive_words_metric": "💤 Mots inactifs",
        "anki_source_metric": "🗃️ Source ANKI",
        "gpt_source_metric": "🤖 Source GPT",
        "import_log_header": "⚠️ Journal d'importation des données",
        "import_log_warning": "Des problèmes ont été détectés lors de la lecture des fichiers de données. Les lignes/fichiers suivants ont été ignorés :",
        "vocab_manager_header": "🗂️ Gestionnaire de vocabulaire",
        "filter_by_source": "Filtrer par source :",
        "filter_by_date": "Filtrer par date d'ajout :",
        "delete_filtered_button": "🗑️ Supprimer tout ce qui est filtré",
        "show_exercise_details": "Afficher les détails par exercice",
        "col_active": "Actif ?",
        "col_delete": "Suppr. ?",
        "col_word": "Mot",
        "col_source": "Source",
        "col_progress": "Progrès",
        "col_status": "Statut",
        "col_status_help": "🏆 indique le nombre de fois que le mot a été maîtrisé !",
        "save_active_status_button": "💾 Enregistrer le statut 'Actif'",
        "delete_selected_button": "🗑️ Supprimer la sélection",
        "written_texts_log_header": "✍️ Journal des textes écrits",
        "cloze_texts_manager_header": "📝 Gestionnaire de textes Cloze",
        "danger_zone_header": "⚠️ Zone de Danger",
        "danger_zone_warning": "L'action ci-dessous est irréversible et effacera TOUT votre historique de performance.",
        "clear_history_button": "🗑️ Effacer TOUT l'historique",
        "no_cloze_in_memory": "Aucun exercice de type '7-Cloze-Text' trouvé en mémoire.",
        "delete_cloze_button": "🗑️ Supprimer les textes Cloze sélectionnés",
        "no_cloze_selected_for_deletion": "Aucun texte Cloze n'a été marqué pour suppression.",

        # Cloze Quiz
        "no_cloze_exercises_found": "Aucun exercice de type '7-Cloze-Text' trouvé dans les données.",
        "select_cloze_text": "Sélectionnez le texte que vous souhaitez pratiquer :",
        "cloze_info": "Remplissez chaque [GAP] avec une des options. Une option ne peut être utilisée qu'une seule fois.",
        "check_answers_button": "✔️ Vérifier les réponses",
        "clear_answers_button": "🔄 Effacer les réponses",
        "practice_another_text_button": "🔄 Pratiquer un autre texte",

        # Sentence Writing Module
        "sentence_writing_title": "Pratique d'Écriture de Phrases ✍️",
        "no_sentence_words_found": "⚠️ Aucun mot trouvé dans 'palavras_unicas_por_tipo.txt'. Veuillez créer le fichier.",
        "stats_header": "📊 Statistiques",
        "total_words_metric_sentence": "Mots Totaux",
        "completed_words_metric": "Terminés (5/5)",
        "partial_words_metric": "En Cours (1-4)",
        "untouched_words_metric": "Intacts (0/5)",
        "word_selection_header": "🔍 Sélection de Mots",
        "filter_by_status": "Filtrer par statut :",
        "choose_word_sentence": "Ou choisir un mot spécifique :",
        "class_level_label": "Classe",
        "reference_sentence_label": "Référence",
        "your_sentences_header": "Vos Phrases",
        "feedback_header": "Commentaires / Feedback",
        "save_button_sentence": "💾 Enregistrer les Phrases & Commentaire",
        "save_success_sentence": "✅ Enregistré avec succès pour le mot '{word}' !",
        "export_options_header": "📤 Options d'Exportation",
        "export_all_button": "Télécharger Toutes les Phrases (TXT)",
        "export_filtered_button": "Télécharger Filtrés (TXT)",
        "feedback_placeholder": "Commentaires ici...",
        "no_words_in_filter": "Aucun mot pour ce filtre",
        "filter_by_level": "Filtrer par Niveau :",
        "filter_by_class": "Filtrer par Classe :",
        "activity_chart_header": "📊 Activité Quotidienne",
        "last_30_days_activity_title": "Phrases Écrites au Cours des 30 Derniers Jours",
        "no_activity_data": "Aucune activité d'écriture enregistrée pour le moment. Commencez à écrire des phrases !",
        "delete_word_data_button": "🗑️ Supprimer Données",
        "delete_word_data_success": "Toutes les données de phrase pour '{word}' ont été supprimées.",
        "grade_label": "Note (0-10)",
        "correction_label": "Correction",
        "average_grade_label": "Note Moyenne",
        "corrected_checkbox": "Corrigé ✅",
        "include_comments_toggle": "Inclure les Commentaires",
        "filter_by_correction_label": "Filtrer par statut de correction :",
        "all_sentences": "Toutes",
        "corrected_sentences": "Corrigées",
        "not_corrected_sentences": "Non Corrigées",
        "include_corrections_toggle": "Inclure les Corrections",
        "include_grades_toggle": "Inclure les Notes",

    }
}

def get_text(key, lang, **kwargs):
    """
    Retorna o texto traduzido para a chave e idioma fornecidos.
    Usa inglês como padrão se a tradução não for encontrada.
    Permite formatação de string com argumentos de palavra-chave.
    """
    default_lang = 'en' if lang not in ['en', 'fr'] else lang
    text_template = TRANSLATIONS.get(default_lang, TRANSLATIONS['en']).get(key, f"<{key}_NOT_FOUND>")
    
    if kwargs:
        return text_template.format(**kwargs)
    return text_template